config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/csrf" => "application#csrf"
  get "/news.xml" => "news#index", format: "xml"

  %w[companies developers members roadmap rubygems team].each do |page|
    get "/#{page}" => "home##{page}"
  end

  redirects = {
    "/benefits" => "/",
    "/contact" => "/",
    "/friends" => "/developers",
    "/join" => "/#join",
    "/plans" => "/roadmap",
    "/projects" => "/roadmap",
    "/why" => "/developers",
    "/membership/new" => "/companies"
  }

  redirects.each do |page, destination|
    get page, to: redirect(destination)
  end

  scope :thanks, as: :thanks do
    %w[friend member newsletter].each do |page|
      get "/#{page}" => "thanks##{page}"
    end
  end

  resource :charge, only: [:create]
  resource :membership, only: [:create, :show, :update, :destroy] do
    collection { post :card }
  end
  resources :news, only: [:index, :show]

  mount StripeEvent::Engine, at: "/stripe/events"
  devise_for :users, path: "", controllers: {sessions: "sessions"}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  after_action :set_cache_control_headers

  def index
    @individuals = Membership.individual.named.order('random()').limit(3).active.pluck(:name)
    @companies = featured_companies.order('random()').limit(5).pluck(:name, :url)
  end

  def members
    set_surrogate_key_header("members")
    @featured_companies = featured_companies.order(:created_at).
      pluck(:name, :description, :url)
    @other_companies = Membership.nonfeatured_companies.named.active.order(:created_at).pluck(:name, :url)
    @individual = Membership.individual.named.active.order(:created_at).pluck(:name)
    @individual_count = Membership.individual.active.count
  end

  private
  def featured_companies
    Membership.featured_companies.named.active
  end

end

app/views/home/_faq.html.erb
<section id="faq" class="group">
  <h2>FAQ</h2>

  <p class="callout">Who is Ruby Together paying?</p>

  <p>Expert Ruby developers that the community knows and trusts, with a years-long track record of improving these tools. Our entire team is listed on the <%= link_to "team page", team_path %>.</p>

  <p class="callout">How will my money be spent?</p>

  <p>As a member, you'll vote directors on to the Ruby Together <%= link_to "board of directors", team_path(anchor: "board") %> every year. The board members you vote for will decide which projects to fund. Our current projects are listed on the <%= link_to "roadmap", roadmap_path(anchor: "upcoming-projects") %>.</p>

  <p class="callout">Will this be a Ruby fundraising disaster?</p>

  <p>We're completely open about the projects that we're working on, and the progress that we've made so far. Unlike other fundraisers, we take funds and post <%= link_to "public updates", news_index_path %> every single month. If at any time you don't think our work is worth your money, you can stop supporting it. Easy peasy.</p>

  <%= content_for :corporate_faq %>

  <p class="callout">What about Ruby Central?</p>

  <p>Ruby Together and <%= link_to "Ruby Central", "http://rubycentral.org" %> work together to support the Ruby community via <%= link_to "the RubyGems partnership", rubygems_path %>.

  <p class="callout">Are contributions tax deductible?</p>

  <p>Yes, membership dues should be tax deductible as long as you use Ruby as part of your business. Check with your accountant to be sure, and let them know that Ruby Together is a 501(c)(6) non-profit trade association.</p>
</section>

app/views/home/_funding_levels.html.erb
<section>
  <h3>Fundraising Progress</h3>

  <%= render "funding_progress_bar" %>

  <%= render "fundraising_goals" %>
</section>

app/views/home/_funding_progress_bar.html.erb
<section class="progress-bar">
  <section class="progress-bar-entry">
    <p class="amount">$50k+</p>
    <p class="title">Rapid Improvements</p>
    <ul>
      <li>Hire a second full-time dev to focus on Ruby, Rails, &amp; other projects</li>
    </ul>
  </section>

  <section class="progress-bar-entry">
    <p class="amount">$35-50k</p>
    <p class="title">Steady Improvements</p>
    <ul>
      <li>Hire a full-time dev to improve gem tools</li>
      <li>Create a public Ruby ecosystem analytics dashboard</li>
      <li>Merge Bundler and RubyGems into a single, unified project</li>
      <li>Expand RubyBench to comprehensively cover Ruby, Rails, and Bundler</li>
    </ul>
  </section>

  <section class="progress-bar-entry">
    <p class="amount">$20-35k</p>
    <p class="title">Slow Improvements</p>
    <ul>
      <li>3 devs at 1-2 days per week</li>
      <li>Maintain Bundler, RubyGems, and RubyGems.org</li>
      <li>Continuous improvements, as long as nothing unusual goes wrong</li>
    </ul>
  </section>

  <section class="progress-bar-entry">
    <p class="amount">$10-20k</p>
    <p class="title">Limited Maintenance</p>
    <ul>
      <li>2-3 devs at 5 hours per week</li>
      <li>Maintain Bundler and RubyGems.org</li>
      <li>No maintenance on RubyGems</li>
      <li>Improvements only from volunteers</li>
    </ul>
  </section>

  <section class="progress-bar-entry">
    <p class="amount">$0-10k</p>
    <p class="title">Volunteers</p>
    <ul>
      <li>Maintenance as time permits</li>
      <li>Fixes take days or weeks</li>
      <li>Improvements take months or years</li>
    </ul>
  </section>
</section>

app/views/home/_fundraising_goals.html.erb
<section id="fundraising_goals">
  <p>
    We have ambitious fundraising goals, and as we hit them we will kick off even bigger projects:

    <ul>
      <li>Create a public Ruby ecosystem analytics dashboard, including Ruby version usage, Bundler version usage, and dramatically expanded statistics for each gem</li>
      <li>Merge Bundler and RubyGems to stop bugs due to mismatched versions forever</li>
      <li>Expand RubyBench.org into a public benchmark for every commit of Bundler, Rails, and Ruby itself</li>
    </ul>

    Those are just examples, and there's a lot more.
  </p>

  <p>When we hit $35k per month, we'll not only have developers maintaining every core tool, we'll have someone working to improve those tools full time as well. When we hit $50k per month, we'll hire a second full-time developer to focus on maintaining and improving Rails and Ruby itself.</p>

  <p>Ruby needs this, and your help is critical to get it done.</p>
</section>

app/views/home/_join.html.erb
<section id="join" class="group">
  <div class="join-box center">
    <p class="title">Developers</p>
    <%= link_to_plan "Back Ruby Together", "individual", class: "solid-button" %>
    <p>$40 per month</p>
    <p class="learn-more"><%= link_to "Learn More", developers_path %></p>
  </div>

  <div class="join-box center">
    <p class="title">Companies</p>
    <%= link_to "Back Ruby Together", companies_path(anchor: "plans"), class: "solid-button" %>
    <p>From $50 per month</p>
    <p class="learn-more"><%= link_to "Learn More", companies_path %></p>
  </div>
</section>

app/views/home/_member_benefit_items.html.erb
<li>Monthly <%= link_to "progress updates", news_index_path %> showing exactly where your money goes. We'll use it wisely, and you'll see how.</li>
<li>Voting rights to elect Ruby Together <%= link_to "board members", team_path(anchor: "board") %>, who decide which projects to fund are most in the members' interests.</li>
<li>Access to some of the best Ruby developers in the world. Chat with other members and the Ruby Together team in our members-only Slack channel.</li>

app/views/home/_progress_so_far.html.erb
<section id="progress">
  <h3>Significant Progress</h3>
  <p>
    In our first year, Ruby Together has completed significant improvements to the infrastructure that Ruby developers use every day:
  </p>
  <ul>
    <li>
      Shipped Bundler versions 1.10, 1.11, and 1.12, featuring conditional gems, optional groups, and a new gem index that can scale to handle the next five years of gems.
    </li>
    <li>
      Launched Gemstash 1.0, a server that can cache gems for your datacenter or office or host your private gems.
    </li>
    <li>
      Migrated RubyGems.org to use CDN servers around the world to serve data, speeding up gems for everyone.
    </li>
  </ul>
</section>

app/views/home/_ruby_together_is.html.erb
<section>
  <p class="aside">Ruby Together is a 501(c)(6) non-profit trade association, which makes membership dues tax deductible. (Check with your accountant to be sure, though.)</p>
</section>

app/views/home/companies.html.erb
<% title "Put Better Tools In Your Toolbox" %>

<section class="group">
  <p>Companies rely on robust tools to build the best apps possible, but the volunteers who maintain those critical Ruby tools and infrastructure can't keep up in their free time. All too often, individual companies end up paying full-time engineers to privately work around issues shared by the entire Ruby community.</p>

  <p class="callout">Ruby Together offers a better way.</p>

  <p>Development teams should never have to sit idle because of problems that could be prevented by maintenance. Sometimes, the work that couldn't be done culminates in a disaster, like RubyGems.org going down for days.</p>

  <p>Companies shouldn't have to pay full-time developers to work on private solutions to public issues. Ruby Together provides a model where companies can spend more time building great apps, instead of spending time on the tools that make those apps possible.</p>
</section>

<section class="group center">
  <%= link_to "Support Ruby Together's work!", "#plans", class: "solid-button" %>
</section>

<section class="clearfix">
  <p class="callout">When you support Ruby Together, you get:</p>

  <ul>
    <li>Top-notch work on the Ruby tools your developers use, for a miniscule fraction of the costs involved.</li>
    <%= render "member_benefit_items" %>
  </ul>

  <p><%= link_to "Our team", team_path %> has a proven track record of delivering year-over-year improvements to Ruby's <%= link_to "public infrastructure", roadmap_path %>. With funding, we'll transform the tools you use so that they work for you. Like tools should.</p>
</section>

<section id="plans" class="group">
  <% %w(onyx jade topaz emerald sapphire ruby).each do |membership| %>
    <%= render "home/memberships/#{membership}" %>
  <% end %>
</section>

<%= render "ruby_together_is" %>

<% content_for :corporate_faq do %>
  <p class="callout">Why do you limit how much I can give?</p>

  <p>Ruby Together deliberately spreads the costs across many companies so that a single company’s actions can't bring an end to work on the tools everyone shares. If a company decides to stop funding our work, we remain financially solvent and can continue our development work without interruption.</p>

  <p class="callout">Why not hire an internal tools developer?</p>

  <p>You could, but it’s less expensive to outsource your Ruby tool problems to Ruby Together and let us pay expert developers to fix them for everyone. We estimate that if you give $10K each year, you’ll get a 15x ROI (the estimated cost of a full-time developer if you hired your own to work on tooling).</p>
<% end %>

<%= render 'faq' %>

<section class="center">
  <p>
    <%= link_to "Join Ruby Together", companies_path(anchor: "plans"), class: "solid-button" %>
  </p>
</section>

app/views/home/index.html.erb
<section>
  <p class="center super-callout">Community funded developer infrastructure</p>

  <p>Ruby Together is a grassroots initiative commited to supporting the critical Ruby infrastructure you rely on: Bundler, RubyGems, and other shared tools.</p>

  <p>
    Join companies like
    <%= @companies.map { |company, url| link_to(company, url) }.to_sentence.html_safe %>;
    individuals like
    <%= @individuals.map { |individual| content_tag(:strong, individual) }.to_sentence.html_safe %>;
    plus <%= link_to "many others", members_path %> supporting the Ruby ecosystem.
  </p>
</section>

<section>
  <h3>Our goal</h3>

  <ul>
    <li>Your financial backing allows Ruby Together to pay expert, professional developers to work on improving <%= link_to "critical infrastructure projects", roadmap_path %>.</li>
    <li>The Ruby Together <%= link_to "board of directors", team_path %>, elected by members, selects the most impactful projects to fund.</li>
    <li>Ruby Together publishes <%= link_to "monthly updates", news_index_path %> showing progress and our proven results.</li>
  </ul>
</section>

<%= render "progress_so_far" %>

<p class="center super-callout">Let's improve Ruby, together!</p>

<%= render "join" %>

<%= render "funding_levels" %>

<section class="clearfix group">
  <blockquote>
    <p class="quote">The more contributors can live off their open-source work, the more they'll be able to devote to that work and the better their software will be for everyone. This is why we've been contributing funds to the open-source infrastructure we rely on.</p>
    <p class="attribution">— Andreas Fuchs, Stripe</p>
  </blockquote>
</section>

<%= render "join" %>

app/views/home/members.html.erb
<%- title "Ruby Together Members" -%>

<section class="group">
  <h3>Corporate Members</h3>

  <% @featured_companies.each do |name, desc, url| %>
    <h4 class="company-name"><%= link_to_if url.present?, name, url %></h3>
    <p class="company-description"><%= desc %></p>
  <% end %>

  <p>
    As well as
    <%= @other_companies.map { |name, url| link_to_if(url.present?, name, url) }.to_sentence.html_safe %>.
  </p>

  <p class="center">Didn’t see your company’s name? <%= link_to "Add it!", companies_path %></p>
</section>

<section class="group">
  <h3>Developer Members</h3>
  <%- @individual << link_to("viewers like you", developers_path) -%>
  <p>
    Our <%= @individual_count %> <%= "developer member".pluralize(@individual_count) %>
    include <%= @individual.to_sentence.html_safe %>.
  </p>

  <p class="center">
    <%= link_to "Become a member today!", developers_path, class: "solid-button" %>
  </p>
</section>

app/views/home/roadmap.html.erb
<% title "Ruby Together roadmap" %>

<p class="callout">Take a look at where we're headed.</p>

<section class="group">
  <h3 id="focus-areas">Focus Areas</h3>

  <p>Today, Ruby Together is committed to improving the three most widely-used core Ruby tools:</p>

  <ul>
    <li><b>Bundler</b>, the Ruby dependency manager, used by every Ruby project to manage and install gems</li>
    <li><b>RubyGems</b>, the code that makes it possible to create gems in the first place</li>
    <li><b>RubyGems.org</b>, the website that provides free hosting for public gems</li>
  </ul>
</section>


<section class="group">
  <h3 id="upcoming-projects">Upcoming Projects</h3>

  <p>As time and funding permits, the Ruby Together team will:</p>

  <ul>
    <li>Roll out a <%= link_to "new gem index", "http://andre.arko.net/2014/03/28/the-new-rubygems-index-format/" %> that will make installing gems two to ten times faster than today</li>
    <li>Migrate all of RubyGems.org to the <%= link_to "Fastly CDN", "http://fastly.com" %>, providing dramatic speed improvements when downloading gems and gem data</li>
    <li>Build a gem caching server to easily allow data centers and offices to cache local copies of the gems they need, whether public or private</li>
    <li>Improve <%= rubygems_org %>, adding search, statistics, and more gem information to every page</li>
  </ul>

  <p>And there will be more! We start new projects based on community need and Ruby Together's available funding.</p>
</section>

<%= render "funding_levels" %>

<%= render "join" %>

app/views/home/rubygems.html.erb
<% title "Rubygems Partnership" %>

<p>The Rubygems Partnership is a cooperative effort between Ruby Central and Ruby Together to ensure that <%= rubygems_org %> is funded, stable, maintained, and supported.</p>

<p><%= link_to "Ruby Central", "http://rubycentral.org" %>, organizers of the international RubyConf and RailsConf conferences, own the <%= rubygems_org %> service. They underwrite hosting costs and ensure that the service is able to continue long-term without needing any external source of funding.</p>

<p><%= link_to "Ruby Together", "http://rubytogether.org" %> provides funding and coordination for ongoing development, maintenance, and support work, as well as on-call system administrators. This ensures that the service continues to mature, grow, and improve, as well as ensuring that everything continues to run in tip-top shape.</p>

app/views/home/team.html.erb
<%- title "Ruby Together Team" -%>

<section class="group">
  <p>Ruby Together funds ongoing work by a team consisting of:</p>

  <ul>
    <li><%= link_to "André Arko", "http://twitter.com/indirect" %>, who maintains and develops <%= bundler %>, as well as contributing to <%= rubygems %> and <%= rubygems_org %>.</li>
    <li><%= link_to "David Radcliffe", "http://twitter.com/dwradcliffe" %>, who maintains and develops <%= rubygems_org %>, as well as the servers that run it.</li>
    <li><%= link_to "Ellen Marie Dash", "http://twitter.com/duckinator" %>, <%= link_to "Kurtis Rainbolt-Greene", "http://twitter.com/krainboltgreene" %>, and <%= link_to "Jeremy Hingardner", "http://twitter.com/copiousfreetime" %>, who together maintain the <%= rubygems %> library and the <code>gem</code> command.</li>
    <li><%= link_to "Samuel E. Giddins", "http://twitter.com/segiddins" %>, who maintains <%= link_to "Molinillo", "https://github.com/CocoaPods/Molinillo" %>, the dependency resolver used by <%= bundler %>, <%= rubygems %>, and <%= link_to "CocoaPods", "https://cocoapods.org" %>, and contributes to each of those projects.</li>
    <li><%= link_to "Lynn Cyrin", "http://twitter.com/lynncyrin" %>, who manages organization, issues, timelines, and updates</li>
  </ul>
</section>

<section class="group">
  <p>The Ruby Together board of directors is made up entirely of volunteers. The board currently includes:</p>

  <ul>
    <li><%= link_to "André Arko", "http://twitter.com/indirect" %></li>
    <li><%= link_to "Steve Klabnik", "http://twitter.com/steveklabnik" %></li>
    <li><%= link_to "Sarah Mei", "http://twitter.com/sarahmei" %></li>
    <li><%= link_to "Terence Lee", "http://twitter.com/hone02" %></li>
    <li><%= link_to "Ines Sombra", "http://twitter.com/randommood" %></li>
    <li><%= link_to "Joel Watson", "http://twitter.com/watsonian" %></li>
    <li><%= link_to "Coraline Ada Ehmke", "http://twitter.com/coralineada" %></li>
  </ul>

  <p>Board alumni include:</p>
  <ul>
    <li><%= link_to "Aaron Patterson", "http://twitter.com/tenderlove" %></li>
  </ul>
</section>

<section class="group">
  <p>Branding and site design are by <%= link_to "Amy Wibowo", "http://sailorhg.com" %>, with copywriting and content strategy by <%= link_to "Rachel Keranen", "http://rachelkeranen.com" %>.</p>
</section>