config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/csrf" => "application#csrf"
  get "/news.xml" => "news#index", format: "xml"

  %w[companies developers members roadmap rubygems team].each do |page|
    get "/#{page}" => "home##{page}"
  end

  redirects = {
    "/benefits" => "/",
    "/contact" => "/",
    "/friends" => "/developers",
    "/join" => "/#join",
    "/plans" => "/roadmap",
    "/projects" => "/roadmap",
    "/why" => "/developers",
    "/membership/new" => "/companies"
  }

  redirects.each do |page, destination|
    get page, to: redirect(destination)
  end

  scope :thanks, as: :thanks do
    %w[friend member newsletter].each do |page|
      get "/#{page}" => "thanks##{page}"
    end
  end

  resource :charge, only: [:create]
  resource :membership, only: [:create, :show, :update, :destroy] do
    collection { post :card }
  end
  resources :news, only: [:index, :show]

  mount StripeEvent::Engine, at: "/stripe/events"
  devise_for :users, path: "", controllers: {sessions: "sessions"}
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  after_action :set_cache_control_headers

  def index
    @posts = Post.all
    @posts.reject!(&:draft) if Rails.env.production?
  end

  def show
    name = sanitize_filename(params[:id])
    render inline: Post.find!(name).body, type: "md", layout: "news"
  end

private

  def sanitize_filename(id)
    id.strip.tap do |name|
      # NOTE: File.basename doesn't work right with Windows paths on Unix
      # get only the filename, not the whole path
      name.sub! /\A.*(\\|\/)/, ''
      # Finally, replace all non alphanumeric, underscore
      # or periods with underscore
      name.gsub! /[^\w\.\-]/, '_'
    end
  end

end

app/views/news/index.html.erb
<% title "Ruby Together News" %>

<p class="center">Monthly progress reports and other Ruby Together updates. See exactly what we’re doing with with the money we raise.</p>

<% @posts.group_by(&:date).each do |date, posts| %>
  <p class="post-date"><%= date.strftime("%B %e, %Y") %></p>
  <ul class="post-names">
  <% posts.each do |post| %>
    <li>
      <%= link_to post.title, news_path(post.id), class: "post-name" %>
      <% if post.summary %>
        <p class="post-summary">
          <%= post.summary %>
          <%= link_to "read more…", news_path(post.id) %>
        </p>
      <% end %>
    </li>
  <% end %>
  </ul>
<% end %>