config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/csrf" => "application#csrf"
  get "/news.xml" => "news#index", format: "xml"

  %w[companies developers members roadmap rubygems team].each do |page|
    get "/#{page}" => "home##{page}"
  end

  redirects = {
    "/benefits" => "/",
    "/contact" => "/",
    "/friends" => "/developers",
    "/join" => "/#join",
    "/plans" => "/roadmap",
    "/projects" => "/roadmap",
    "/why" => "/developers",
    "/membership/new" => "/companies"
  }

  redirects.each do |page, destination|
    get page, to: redirect(destination)
  end

  scope :thanks, as: :thanks do
    %w[friend member newsletter].each do |page|
      get "/#{page}" => "thanks##{page}"
    end
  end

  resource :charge, only: [:create]
  resource :membership, only: [:create, :show, :update, :destroy] do
    collection { post :card }
  end
  resources :news, only: [:index, :show]

  mount StripeEvent::Engine, at: "/stripe/events"
  devise_for :users, path: "", controllers: {sessions: "sessions"}
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  after_action :set_cache_control_headers
end

app/views/thanks/friend.html.erb
<% title "Thank you!" %>

<p>Thank you for donating to Ruby Together! Your support makes Ruby better for everyone.</p>

<p>Please take a moment and encourage your Ruby friends to join Ruby Together, too. More support for Ruby Together means we can give back more awesome to the Ruby community.</p>

<p class="center"><%= joined_tweet_link "Tweet about Ruby Together" %>, or <%= joined_mail_link "send an email" %>!</p>

<% content_for(:footer, "<br>".html_safe) %>

app/views/thanks/member.html.erb
<% title "You're a gem!" %>

<p>Thank you for joining Ruby Together! Your support means the world to us. ❤️</p>

<p>If you would like your name to appear in the <%= link_to "list of members", members_path %>, you can add or update your membership details on the <%= link_to "manage your membership", membership_path %> page. We've sent you an email with a link as well, in case you need to return later.</p>

<p>Please take a moment and encourage your Ruby friends to join Ruby Together, too. More support for Ruby Together means we can give back more awesome to the Ruby community.</p>

<p class="center"><%= joined_tweet_link "Tweet about Ruby Together" %>, or <%= joined_mail_link "send an email" %>!</p>

<% content_for(:footer, "<br>".html_safe) %>

app/views/thanks/newsletter.html.erb
<% title "Thanks a million!" %>

<p>We’re honored that you want our face in your email inbox. Please check your email and click the link provided to confirm your subscription.</p>

<p class="center">
  Follow us on Twitter and GitHub, too!<br>
  <%= link_to iconic_tag("social-twitter-md"), "https://twitter.com/rubytogether" %>
  <%= link_to iconic_tag("social-github-md"), "https://github.com/rubytogether" %>
</p>


<p class="aside">We promise we’ll never spam you or sell your information, and you can unsubscribe from our email updates at any time.</p>

<% content_for(:footer, "<br>".html_safe) %>